substitutions:
  name: "dak-keg-scale"
  friendly_name: "Dak Keg Scale"
  project_name: "Dak Enterprises.Dak Keg Scale"
  project_version: "0.1.1"
  
esp32:
  board: esp32dev
  framework:
    type: esp-idf

packages:
  basescale: !include common/basescale.yaml
