substitutions:
  name: "dak-keg-scale"
  friendly_name: "Dak Keg Scale"
  project_name: "Dak Keg Scale"
  project_version: "0.0.1"
  
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

packages:
  basescale: !include common/basescale.yaml


