substitutions:
  name: "dak-keg-scale"
  friendly_name: "Dak Keg Scale"
  project_name: "Dak Enterprises.Dak Keg Scale"
  project_version: "0.2.0"
  
esp32:
#  board: esp32-c6-devkitm-1
  board: esp32-c6-devkitc-1
  framework:
    type: arduino

packages:
  basescale: !include common/basescale.yaml
  ble_server: !include common/ble_server.yaml
