substitutions:
  name: "dak-keg-scale"
  friendly_name: "Dak Keg Scale"
  project_name: "Dak Enterprises.Dak Keg Scale"
  project_version: "0.0.1"
  
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

packages:
  basescale: !include common/basescale.yaml
  
wifi:
  # Set up a wifi access point using the device name above
  ap:
    ssid: "KegScaleWifi"
    password: "MMMMBeer"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:
