substitutions:
  name: "dak-keg-scale"
  friendly_name: "Dak Keg Scale"
  project_name: "Dak Enterprises.Dak Keg Scale"
  project_version: "0.1.1"
  
esp32:
  board: nodemcu-32s
  framework:
    type: arduino

packages:
  basescale: !include common/basescale.yaml
  ble_server: !include common/ble_server.yaml
